apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-create
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/tranthang2404/clusterapi-azure-demo.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-cluster-01.yaml
  project: default