cluster:
  name: cluster-01
  masterNodes: 1
  workerNodes: 1
  version: v1.24.0
azure:
  location: southeastasia
  cluster-identity: cluster-identity
  subscriptionID: 7a0440e3-e49c-4322-a71e-4eb425c34f6c
  vmSize: Standard_B2s
  sshPublicKey: ""